/* Generated By:JavaCC: Do not edit this line. CCJSqlParserTreeConstants.java Version 7.0.10 */
package net.sf.jsqlparser.parser;

public interface CCJSqlParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTVOID = 1;
  public int JJTBLOCK = 2;
  public int JJTSTATEMENTS = 3;
  public int JJTCOLUMN = 4;
  public int JJTTABLE = 5;
  public int JJTPLAINSELECT = 6;
  public int JJTSETOPERATIONLIST = 7;
  public int JJTWITHITEM = 8;
  public int JJTSELECTITEM = 9;
  public int JJTJOINEREXPRESSION = 10;
  public int JJTLIMITWITHOFFSET = 11;
  public int JJTPLAINLIMIT = 12;
  public int JJTEXPRESSION = 13;
  public int JJTREGULARCONDITION = 14;
  public int JJTINEXPRESSION = 15;
  public int JJTLIKEEXPRESSION = 16;
  public int JJTSIMILARTOEXPRESSION = 17;
  public int JJTEXPRESSIONLIST = 18;
  public int JJTPRIMARYEXPRESSION = 19;
  public int JJTCASEWHENEXPRESSION = 20;
  public int JJTFUNCTION = 21;
  public int JJTSUBSELECT = 22;
  public int JJTSEQUENCE = 23;
  public int JJTSYNONYM = 24;


  public String[] jjtNodeName = {
    "Statement",
    "void",
    "Block",
    "Statements",
    "Column",
    "Table",
    "PlainSelect",
    "SetOperationList",
    "WithItem",
    "SelectItem",
    "JoinerExpression",
    "LimitWithOffset",
    "PlainLimit",
    "Expression",
    "RegularCondition",
    "InExpression",
    "LikeExpression",
    "SimilarToExpression",
    "ExpressionList",
    "PrimaryExpression",
    "CaseWhenExpression",
    "Function",
    "SubSelect",
    "Sequence",
    "Synonym",
  };
}
/* JavaCC - OriginalChecksum=841b60d330fc765d4526a9ef4ff56ade (do not edit this line) */
