/*-
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2021 JSQLParser
 * %%
 * Dual licensed under GNU LGPL 2.1 or Apache License 2.0
 * #L%
 */
/* Generated By:JJTree&JavaCC: Do not edit this line. CCJSqlParserConstants.java */
package net.sf.jsqlparser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCJSqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int K_ACTION = 2;
  /** RegularExpression Id. */
  int K_ADD = 3;
  /** RegularExpression Id. */
  int K_ADVANCE = 4;
  /** RegularExpression Id. */
  int K_AGAINST = 5;
  /** RegularExpression Id. */
  int K_ALGORITHM = 6;
  /** RegularExpression Id. */
  int K_ALL = 7;
  /** RegularExpression Id. */
  int K_ALTER = 8;
  /** RegularExpression Id. */
  int K_ANALYZE = 9;
  /** RegularExpression Id. */
  int K_AND = 10;
  /** RegularExpression Id. */
  int K_AND_OPERATOR = 11;
  /** RegularExpression Id. */
  int K_ANY = 12;
  /** RegularExpression Id. */
  int K_APPLY = 13;
  /** RegularExpression Id. */
  int K_AS = 14;
  /** RegularExpression Id. */
  int K_ASC = 15;
  /** RegularExpression Id. */
  int K_AUTHORIZATION = 16;
  /** RegularExpression Id. */
  int K_BEGIN = 17;
  /** RegularExpression Id. */
  int K_BETWEEN = 18;
  /** RegularExpression Id. */
  int K_BINARY = 19;
  /** RegularExpression Id. */
  int K_BIT = 20;
  /** RegularExpression Id. */
  int K_BOTH = 21;
  /** RegularExpression Id. */
  int K_BY = 22;
  /** RegularExpression Id. */
  int K_CACHE = 23;
  /** RegularExpression Id. */
  int K_BUFFERS = 24;
  /** RegularExpression Id. */
  int K_BYTE = 25;
  /** RegularExpression Id. */
  int K_CALL = 26;
  /** RegularExpression Id. */
  int K_CASCADE = 27;
  /** RegularExpression Id. */
  int K_CASE = 28;
  /** RegularExpression Id. */
  int K_CASEWHEN = 29;
  /** RegularExpression Id. */
  int K_CAST = 30;
  /** RegularExpression Id. */
  int K_CHARACTER = 31;
  /** RegularExpression Id. */
  int K_CHANGE = 32;
  /** RegularExpression Id. */
  int K_CHECK = 33;
  /** RegularExpression Id. */
  int K_CHAR = 34;
  /** RegularExpression Id. */
  int K_COLLATE = 35;
  /** RegularExpression Id. */
  int K_COLUMN = 36;
  /** RegularExpression Id. */
  int K_COLUMNS = 37;
  /** RegularExpression Id. */
  int K_COMMA = 38;
  /** RegularExpression Id. */
  int K_COMMIT = 39;
  /** RegularExpression Id. */
  int K_COMMENT = 40;
  /** RegularExpression Id. */
  int K_CONNECT = 41;
  /** RegularExpression Id. */
  int K_CONSTRAINT = 42;
  /** RegularExpression Id. */
  int K_COSTS = 43;
  /** RegularExpression Id. */
  int K_CREATE = 44;
  /** RegularExpression Id. */
  int K_CROSS = 45;
  /** RegularExpression Id. */
  int K_CURRENT = 46;
  /** RegularExpression Id. */
  int K_CYCLE = 47;
  /** RegularExpression Id. */
  int K_DECLARE = 48;
  /** RegularExpression Id. */
  int K_DATETIMELITERAL = 49;
  /** RegularExpression Id. */
  int K_DATE_LITERAL = 50;
  /** RegularExpression Id. */
  int K_DEFAULT = 51;
  /** RegularExpression Id. */
  int K_DEFERRABLE = 52;
  /** RegularExpression Id. */
  int K_DELAYED = 53;
  /** RegularExpression Id. */
  int K_DELETE = 54;
  /** RegularExpression Id. */
  int K_DESC = 55;
  /** RegularExpression Id. */
  int K_DESCRIBE = 56;
  /** RegularExpression Id. */
  int K_DISABLE = 57;
  /** RegularExpression Id. */
  int K_DISTINCT = 58;
  /** RegularExpression Id. */
  int K_DIV = 59;
  /** RegularExpression Id. */
  int K_DO = 60;
  /** RegularExpression Id. */
  int K_DOUBLE = 61;
  /** RegularExpression Id. */
  int K_DROP = 62;
  /** RegularExpression Id. */
  int K_DUPLICATE = 63;
  /** RegularExpression Id. */
  int K_ELSE = 64;
  /** RegularExpression Id. */
  int K_ENABLE = 65;
  /** RegularExpression Id. */
  int K_END = 66;
  /** RegularExpression Id. */
  int K_ESCAPE = 67;
  /** RegularExpression Id. */
  int K_EXCEPT = 68;
  /** RegularExpression Id. */
  int K_EXCLUDE = 69;
  /** RegularExpression Id. */
  int K_EXEC = 70;
  /** RegularExpression Id. */
  int K_EXECUTE = 71;
  /** RegularExpression Id. */
  int K_EXISTS = 72;
  /** RegularExpression Id. */
  int K_EXPLAIN = 73;
  /** RegularExpression Id. */
  int K_EXTENDED = 74;
  /** RegularExpression Id. */
  int K_EXTRACT = 75;
  /** RegularExpression Id. */
  int K_FETCH = 76;
  /** RegularExpression Id. */
  int K_FILTER = 77;
  /** RegularExpression Id. */
  int K_FIRST = 78;
  /** RegularExpression Id. */
  int K_FALSE = 79;
  /** RegularExpression Id. */
  int K_FOLLOWING = 80;
  /** RegularExpression Id. */
  int K_FOR = 81;
  /** RegularExpression Id. */
  int K_FORCE = 82;
  /** RegularExpression Id. */
  int K_FOREIGN = 83;
  /** RegularExpression Id. */
  int K_FORMAT = 84;
  /** RegularExpression Id. */
  int K_FROM = 85;
  /** RegularExpression Id. */
  int K_FULL = 86;
  /** RegularExpression Id. */
  int K_FULLTEXT = 87;
  /** RegularExpression Id. */
  int K_FUNCTION = 88;
  /** RegularExpression Id. */
  int K_GLOBAL = 89;
  /** RegularExpression Id. */
  int K_GRANT = 90;
  /** RegularExpression Id. */
  int K_GROUP = 91;
  /** RegularExpression Id. */
  int K_GROUPING = 92;
  /** RegularExpression Id. */
  int K_GROUP_CONCAT = 93;
  /** RegularExpression Id. */
  int K_HAVING = 94;
  /** RegularExpression Id. */
  int K_HIGH_PRIORITY = 95;
  /** RegularExpression Id. */
  int K_HOPPING = 96;
  /** RegularExpression Id. */
  int K_IF = 97;
  /** RegularExpression Id. */
  int K_IIF = 98;
  /** RegularExpression Id. */
  int K_IGNORE = 99;
  /** RegularExpression Id. */
  int K_ILIKE = 100;
  /** RegularExpression Id. */
  int K_IN = 101;
  /** RegularExpression Id. */
  int K_INCLUDE = 102;
  /** RegularExpression Id. */
  int K_INCREMENT = 103;
  /** RegularExpression Id. */
  int K_INDEX = 104;
  /** RegularExpression Id. */
  int K_INNER = 105;
  /** RegularExpression Id. */
  int K_STRAIGHT = 106;
  /** RegularExpression Id. */
  int K_INSERT = 107;
  /** RegularExpression Id. */
  int K_INTERSECT = 108;
  /** RegularExpression Id. */
  int K_INTERVAL = 109;
  /** RegularExpression Id. */
  int K_INTO = 110;
  /** RegularExpression Id. */
  int K_IS = 111;
  /** RegularExpression Id. */
  int K_ISNULL = 112;
  /** RegularExpression Id. */
  int K_JOIN = 113;
  /** RegularExpression Id. */
  int K_JSON = 114;
  /** RegularExpression Id. */
  int K_KEEP = 115;
  /** RegularExpression Id. */
  int K_KEY = 116;
  /** RegularExpression Id. */
  int K_FN = 117;
  /** RegularExpression Id. */
  int K_LAST = 118;
  /** RegularExpression Id. */
  int K_LATERAL = 119;
  /** RegularExpression Id. */
  int K_LEADING = 120;
  /** RegularExpression Id. */
  int K_LEFT = 121;
  /** RegularExpression Id. */
  int K_LIKE = 122;
  /** RegularExpression Id. */
  int K_LIMIT = 123;
  /** RegularExpression Id. */
  int K_LOW_PRIORITY = 124;
  /** RegularExpression Id. */
  int K_MATCH = 125;
  /** RegularExpression Id. */
  int K_MATCHED = 126;
  /** RegularExpression Id. */
  int K_MATERIALIZED = 127;
  /** RegularExpression Id. */
  int K_MAXVALUE = 128;
  /** RegularExpression Id. */
  int K_MERGE = 129;
  /** RegularExpression Id. */
  int K_MINUS = 130;
  /** RegularExpression Id. */
  int K_MINVALUE = 131;
  /** RegularExpression Id. */
  int K_MODIFY = 132;
  /** RegularExpression Id. */
  int K_MOVEMENT = 133;
  /** RegularExpression Id. */
  int K_NATURAL = 134;
  /** RegularExpression Id. */
  int K_NEXT = 135;
  /** RegularExpression Id. */
  int K_NEXTVAL = 136;
  /** RegularExpression Id. */
  int K_NO = 137;
  /** RegularExpression Id. */
  int K_NOCACHE = 138;
  /** RegularExpression Id. */
  int K_NOCYCLE = 139;
  /** RegularExpression Id. */
  int K_NOKEEP = 140;
  /** RegularExpression Id. */
  int K_NOLOCK = 141;
  /** RegularExpression Id. */
  int K_NOMAXVALUE = 142;
  /** RegularExpression Id. */
  int K_NOMINVALUE = 143;
  /** RegularExpression Id. */
  int K_NOORDER = 144;
  /** RegularExpression Id. */
  int K_NOT = 145;
  /** RegularExpression Id. */
  int K_NOVALIDATE = 146;
  /** RegularExpression Id. */
  int K_NULL = 147;
  /** RegularExpression Id. */
  int K_NULLS = 148;
  /** RegularExpression Id. */
  int K_NOWAIT = 149;
  /** RegularExpression Id. */
  int K_OF = 150;
  /** RegularExpression Id. */
  int K_OFF = 151;
  /** RegularExpression Id. */
  int K_OFFSET = 152;
  /** RegularExpression Id. */
  int K_ON = 153;
  /** RegularExpression Id. */
  int K_ONLY = 154;
  /** RegularExpression Id. */
  int K_OPEN = 155;
  /** RegularExpression Id. */
  int K_OR = 156;
  /** RegularExpression Id. */
  int K_ORDER = 157;
  /** RegularExpression Id. */
  int K_OUTER = 158;
  /** RegularExpression Id. */
  int K_OVER = 159;
  /** RegularExpression Id. */
  int K_OPTIMIZE = 160;
  /** RegularExpression Id. */
  int K_PARTITION = 161;
  /** RegularExpression Id. */
  int K_PATH = 162;
  /** RegularExpression Id. */
  int K_PERCENT = 163;
  /** RegularExpression Id. */
  int K_PIVOT = 164;
  /** RegularExpression Id. */
  int K_PLACING = 165;
  /** RegularExpression Id. */
  int K_PRECEDING = 166;
  /** RegularExpression Id. */
  int K_PRECISION = 167;
  /** RegularExpression Id. */
  int K_PRIMARY = 168;
  /** RegularExpression Id. */
  int K_PRIOR = 169;
  /** RegularExpression Id. */
  int K_PROCEDURE = 170;
  /** RegularExpression Id. */
  int K_PUBLIC = 171;
  /** RegularExpression Id. */
  int K_RANGE = 172;
  /** RegularExpression Id. */
  int K_READ = 173;
  /** RegularExpression Id. */
  int K_RECURSIVE = 174;
  /** RegularExpression Id. */
  int K_REFERENCES = 175;
  /** RegularExpression Id. */
  int K_REGEXP = 176;
  /** RegularExpression Id. */
  int K_RLIKE = 177;
  /** RegularExpression Id. */
  int K_RENAME = 178;
  /** RegularExpression Id. */
  int K_REPLACE = 179;
  /** RegularExpression Id. */
  int K_RESTRICT = 180;
  /** RegularExpression Id. */
  int K_RETURNING = 181;
  /** RegularExpression Id. */
  int K_RIGHT = 182;
  /** RegularExpression Id. */
  int K_ROW = 183;
  /** RegularExpression Id. */
  int K_ROWS = 184;
  /** RegularExpression Id. */
  int K_SCHEMA = 185;
  /** RegularExpression Id. */
  int K_SELECT = 186;
  /** RegularExpression Id. */
  int K_SEMI = 187;
  /** RegularExpression Id. */
  int K_SEQUENCE = 188;
  /** RegularExpression Id. */
  int K_SEPARATOR = 189;
  /** RegularExpression Id. */
  int K_SESSION = 190;
  /** RegularExpression Id. */
  int K_SET = 191;
  /** RegularExpression Id. */
  int K_SETS = 192;
  /** RegularExpression Id. */
  int K_SHOW = 193;
  /** RegularExpression Id. */
  int K_SIBLINGS = 194;
  /** RegularExpression Id. */
  int K_SIMILAR = 195;
  /** RegularExpression Id. */
  int K_SIZE = 196;
  /** RegularExpression Id. */
  int K_SKIP = 197;
  /** RegularExpression Id. */
  int K_SOME = 198;
  /** RegularExpression Id. */
  int K_START = 199;
  /** RegularExpression Id. */
  int K_SYNONYM = 200;
  /** RegularExpression Id. */
  int K_TABLE = 201;
  /** RegularExpression Id. */
  int K_TABLES = 202;
  /** RegularExpression Id. */
  int K_TABLESPACE = 203;
  /** RegularExpression Id. */
  int K_THEN = 204;
  /** RegularExpression Id. */
  int K_TEMP = 205;
  /** RegularExpression Id. */
  int K_TEMPORARY = 206;
  /** RegularExpression Id. */
  int K_TIME_KEY_EXPR = 207;
  /** RegularExpression Id. */
  int K_TO = 208;
  /** RegularExpression Id. */
  int K_TOP = 209;
  /** RegularExpression Id. */
  int K_TRAILING = 210;
  /** RegularExpression Id. */
  int K_TRUNCATE = 211;
  /** RegularExpression Id. */
  int K_TRUE = 212;
  /** RegularExpression Id. */
  int K_TUMBLING = 213;
  /** RegularExpression Id. */
  int K_TYPE = 214;
  /** RegularExpression Id. */
  int K_UNBOUNDED = 215;
  /** RegularExpression Id. */
  int K_UNION = 216;
  /** RegularExpression Id. */
  int K_UNIQUE = 217;
  /** RegularExpression Id. */
  int K_UNLOGGED = 218;
  /** RegularExpression Id. */
  int K_UNPIVOT = 219;
  /** RegularExpression Id. */
  int K_UPDATE = 220;
  /** RegularExpression Id. */
  int K_UPSERT = 221;
  /** RegularExpression Id. */
  int K_USE = 222;
  /** RegularExpression Id. */
  int K_SQL_CALC_FOUND_ROWS = 223;
  /** RegularExpression Id. */
  int K_SQL_NO_CACHE = 224;
  /** RegularExpression Id. */
  int K_USING = 225;
  /** RegularExpression Id. */
  int K_SIGNED = 226;
  /** RegularExpression Id. */
  int K_UNSIGNED = 227;
  /** RegularExpression Id. */
  int K_VALIDATE = 228;
  /** RegularExpression Id. */
  int K_VALUE = 229;
  /** RegularExpression Id. */
  int K_VALUES = 230;
  /** RegularExpression Id. */
  int K_VARYING = 231;
  /** RegularExpression Id. */
  int K_VERBOSE = 232;
  /** RegularExpression Id. */
  int K_VIEW = 233;
  /** RegularExpression Id. */
  int K_WAIT = 234;
  /** RegularExpression Id. */
  int K_WHEN = 235;
  /** RegularExpression Id. */
  int K_WHERE = 236;
  /** RegularExpression Id. */
  int K_WINDOW = 237;
  /** RegularExpression Id. */
  int K_WITH = 238;
  /** RegularExpression Id. */
  int K_WITHIN = 239;
  /** RegularExpression Id. */
  int K_WITHOUT = 240;
  /** RegularExpression Id. */
  int K_XML = 241;
  /** RegularExpression Id. */
  int K_XMLSERIALIZE = 242;
  /** RegularExpression Id. */
  int K_XMLAGG = 243;
  /** RegularExpression Id. */
  int K_XMLTEXT = 244;
  /** RegularExpression Id. */
  int K_YAML = 245;
  /** RegularExpression Id. */
  int K_ZONE = 246;
  /** RegularExpression Id. */
  int K_STATUS = 247;
  /** RegularExpression Id. */
  int ST_SEMICOLON = 248;
  /** RegularExpression Id. */
  int OP_GREATERTHANEQUALS = 249;
  /** RegularExpression Id. */
  int OP_MINORTHANEQUALS = 250;
  /** RegularExpression Id. */
  int OP_NOTEQUALSSTANDARD = 251;
  /** RegularExpression Id. */
  int OP_NOTEQUALSBANG = 252;
  /** RegularExpression Id. */
  int OP_CONCAT = 253;
  /** RegularExpression Id. */
  int DT_ZONE = 254;
  /** RegularExpression Id. */
  int S_DOUBLE = 255;
  /** RegularExpression Id. */
  int S_LONG = 256;
  /** RegularExpression Id. */
  int DIGIT = 257;
  /** RegularExpression Id. */
  int S_HEX = 258;
  /** RegularExpression Id. */
  int HEX_VALUE = 259;
  /** RegularExpression Id. */
  int LINE_COMMENT = 260;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 261;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 262;
  /** RegularExpression Id. */
  int LETTER = 263;
  /** RegularExpression Id. */
  int PART_LETTER = 264;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 265;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 266;
  /** RegularExpression Id. */
  int ESC = 267;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"ACTION\"",
    "\"ADD\"",
    "\"ADVANCE\"",
    "\"AGAINST\"",
    "\"ALGORITHM\"",
    "\"ALL\"",
    "\"ALTER\"",
    "\"ANALYZE\"",
    "\"AND\"",
    "\"&&\"",
    "\"ANY\"",
    "\"APPLY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"AUTHORIZATION\"",
    "\"BEGIN\"",
    "\"BETWEEN\"",
    "\"BINARY\"",
    "\"BIT\"",
    "\"BOTH\"",
    "\"BY\"",
    "\"CACHE\"",
    "\"BUFFERS\"",
    "\"BYTE\"",
    "\"CALL\"",
    "\"CASCADE\"",
    "\"CASE\"",
    "\"CASEWHEN\"",
    "\"CAST\"",
    "\"CHARACTER\"",
    "\"CHANGE\"",
    "\"CHECK\"",
    "\"CHAR\"",
    "\"COLLATE\"",
    "\"COLUMN\"",
    "\"COLUMNS\"",
    "\",\"",
    "\"COMMIT\"",
    "\"COMMENT\"",
    "\"CONNECT\"",
    "\"CONSTRAINT\"",
    "\"COSTS\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CURRENT\"",
    "\"CYCLE\"",
    "\"DECLARE\"",
    "<K_DATETIMELITERAL>",
    "<K_DATE_LITERAL>",
    "\"DEFAULT\"",
    "\"DEFERRABLE\"",
    "\"DELAYED\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DISABLE\"",
    "\"DISTINCT\"",
    "\"DIV\"",
    "\"DO\"",
    "\"DOUBLE\"",
    "\"DROP\"",
    "\"DUPLICATE\"",
    "\"ELSE\"",
    "\"ENABLE\"",
    "\"END\"",
    "\"ESCAPE\"",
    "\"EXCEPT\"",
    "\"EXCLUDE\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"EXPLAIN\"",
    "\"EXTENDED\"",
    "\"EXTRACT\"",
    "\"FETCH\"",
    "\"FILTER\"",
    "\"FIRST\"",
    "\"FALSE\"",
    "\"FOLLOWING\"",
    "\"FOR\"",
    "\"FORCE\"",
    "\"FOREIGN\"",
    "\"FORMAT\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FULLTEXT\"",
    "\"FUNCTION\"",
    "\"GLOBAL\"",
    "\"GRANT\"",
    "\"GROUP\"",
    "\"GROUPING\"",
    "\"GROUP_CONCAT\"",
    "\"HAVING\"",
    "\"HIGH_PRIORITY\"",
    "\"HOPPING\"",
    "\"IF\"",
    "\"IIF\"",
    "\"IGNORE\"",
    "\"ILIKE\"",
    "\"IN\"",
    "\"INCLUDE\"",
    "\"INCREMENT\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"STRAIGHT_JOIN\"",
    "\"INSERT\"",
    "\"INTERSECT\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"IS\"",
    "\"ISNULL\"",
    "\"JOIN\"",
    "\"JSON\"",
    "\"KEEP\"",
    "\"KEY\"",
    "\"FN\"",
    "\"LAST\"",
    "\"LATERAL\"",
    "\"LEADING\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"LIMIT\"",
    "\"LOW_PRIORITY\"",
    "\"MATCH\"",
    "\"MATCHED\"",
    "\"MATERIALIZED\"",
    "\"MAXVALUE\"",
    "\"MERGE\"",
    "\"MINUS\"",
    "\"MINVALUE\"",
    "\"MODIFY\"",
    "\"MOVEMENT\"",
    "\"NATURAL\"",
    "\"NEXT\"",
    "\"NEXTVAL\"",
    "\"NO\"",
    "\"NOCACHE\"",
    "\"NOCYCLE\"",
    "\"NOKEEP\"",
    "\"NOLOCK\"",
    "\"NOMAXVALUE\"",
    "\"NOMINVALUE\"",
    "\"NOORDER\"",
    "\"NOT\"",
    "\"NOVALIDATE\"",
    "\"NULL\"",
    "\"NULLS\"",
    "\"NOWAIT\"",
    "\"OF\"",
    "\"OFF\"",
    "\"OFFSET\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"OUTER\"",
    "\"OVER\"",
    "\"OPTIMIZE\"",
    "\"PARTITION\"",
    "\"PATH\"",
    "\"PERCENT\"",
    "\"PIVOT\"",
    "\"PLACING\"",
    "\"PRECEDING\"",
    "\"PRECISION\"",
    "\"PRIMARY\"",
    "\"PRIOR\"",
    "\"PROCEDURE\"",
    "\"PUBLIC\"",
    "\"RANGE\"",
    "\"READ\"",
    "\"RECURSIVE\"",
    "\"REFERENCES\"",
    "\"REGEXP\"",
    "\"RLIKE\"",
    "\"RENAME\"",
    "\"REPLACE\"",
    "\"RESTRICT\"",
    "\"RETURNING\"",
    "\"RIGHT\"",
    "\"ROW\"",
    "\"ROWS\"",
    "\"SCHEMA\"",
    "<K_SELECT>",
    "\"SEMI\"",
    "\"SEQUENCE\"",
    "\"SEPARATOR\"",
    "\"SESSION\"",
    "\"SET\"",
    "\"SETS\"",
    "\"SHOW\"",
    "\"SIBLINGS\"",
    "\"SIMILAR\"",
    "\"SIZE\"",
    "\"SKIP\"",
    "\"SOME\"",
    "\"START\"",
    "\"SYNONYM\"",
    "\"TABLE\"",
    "\"TABLES\"",
    "\"TABLESPACE\"",
    "\"THEN\"",
    "\"TEMP\"",
    "\"TEMPORARY\"",
    "<K_TIME_KEY_EXPR>",
    "\"TO\"",
    "\"TOP\"",
    "\"TRAILING\"",
    "\"TRUNCATE\"",
    "\"TRUE\"",
    "\"TUMBLING\"",
    "\"TYPE\"",
    "\"UNBOUNDED\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNLOGGED\"",
    "\"UNPIVOT\"",
    "\"UPDATE\"",
    "\"UPSERT\"",
    "\"USE\"",
    "\"SQL_CALC_FOUND_ROWS\"",
    "\"SQL_NO_CACHE\"",
    "\"USING\"",
    "\"SIGNED\"",
    "\"UNSIGNED\"",
    "\"VALIDATE\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"VARYING\"",
    "\"VERBOSE\"",
    "\"VIEW\"",
    "\"WAIT\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WINDOW\"",
    "\"WITH\"",
    "\"WITHIN\"",
    "\"WITHOUT\"",
    "\"XML\"",
    "\"XMLSERIALIZE\"",
    "\"XMLAGG\"",
    "\"XMLTEXT\"",
    "\"YAML\"",
    "\"ZONE\"",
    "\"STATUS\"",
    "\";\"",
    "<OP_GREATERTHANEQUALS>",
    "<OP_MINORTHANEQUALS>",
    "<OP_NOTEQUALSSTANDARD>",
    "<OP_NOTEQUALSBANG>",
    "<OP_CONCAT>",
    "<DT_ZONE>",
    "<S_DOUBLE>",
    "<S_LONG>",
    "<DIGIT>",
    "<S_HEX>",
    "<HEX_VALUE>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<ESC>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"*\"",
    "\".\"",
    "\"?\"",
    "\":\"",
    "\"!\"",
    "\"+\"",
    "\">\"",
    "\"<\"",
    "\"@@\"",
    "\"~\"",
    "\"~*\"",
    "\"!~\"",
    "\"!~*\"",
    "\"@>\"",
    "\"<@\"",
    "\"?|\"",
    "\"?&\"",
    "\"-\"",
    "\"-#\"",
    "\":=\"",
    "\"|\"",
    "\"&\"",
    "\"<<\"",
    "\">>\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"{d\"",
    "\"}\"",
    "\"{t\"",
    "\"{ts\"",
    "\"[\"",
    "\"]\"",
    "\"::\"",
    "\"@\"",
    "\"->\"",
    "\"->>\"",
    "\"#>\"",
    "\"#>>\"",
    "\"IN NATURAL LANGUAGE MODE\"",
    "\"IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION\"",
    "\"IN BOOLEAN MODE\"",
    "\"WITH QUERY EXPANSION\"",
    "\"{\"",
  };

}
