/* Generated By:JavaCC: Do not edit this line. CCJSqlParserVisitor.java Version 7.0.10 */
package net.sf.jsqlparser.parser;

public interface CCJSqlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=0bc38123953ee2a278919d038489e43b (do not edit this line) */
